Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace dotNetShop.Controllers
{
	public class BlogController : Controller
	{
		// GET: BlogController
		public ActionResult Index()
		{
			return View();
		}

		// GET: BlogController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: BlogController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: BlogController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: BlogController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: BlogController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: BlogController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: BlogController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

Controllers/ShopController.cs
using dotNetShop.Data;
using dotNetShop.Services;
using Microsoft.AspNetCore.Mvc;
using dotNetShop.ViewModels.ShopService;

namespace dotNetShop.Controllers
{
	public class ShopController : Controller
	{

		private readonly IShopService _shopService;
		private readonly ShopDBContext _context;

		public ShopController(IShopService shopService,  ShopDBContext context)
		{
			_shopService = shopService;
			_context = context;	
		}

		// GET: ShopController
		public async Task<IActionResult> Index()
		{
			ShopDBContext.SeedDataShop(_context);
			ShopDBContext.SeedDataContact(_context);
			var viewModel = await _shopService.GetShopAsync();

			return View(viewModel);
		}

		// GET: ShopController/Details/5
		// GET: ProductComments/ProductDetails/{productId}
		public async Task<IActionResult> Details(int Id)
		{
            ProductCommentViewModel viewModel = await _shopService.GetProductByIdAsync(Id);

			if (viewModel.Product == null) return NotFound();
     
			return View(viewModel);
		}

		// POST: ProductComments/AddComment
		//[HttpPost]
		//[ValidateAntiForgeryToken]
		//public async Task<IActionResult> AddComment(ProductCommentViewModel model)
		//{
		//    if (ModelState.IsValid)
		//    {
		//        model.NewComment.ProductId = model.Product.Id;
		//        model.NewComment.CreatedAt = DateTime.UtcNow;

		//        _context.Comments.Add(model.NewComment);
		//        await _context.SaveChangesAsync();

		//        return RedirectToAction("ProductDetails", new { productId = model.Product.Id });
		//    }

		//    // Если валидация не прошла, снова загружаем комментарии
		//    model.Comments = await _context.Comments
		//        .Where(c => c.ProductId == model.Product.Id)
		//        .OrderByDescending(c => c.CreatedAt)
		//        .ToListAsync();

		//    return View("ProductDetails", model);
		//}
	}
}

Views/Shared/_Layout.cshtml
@addTagHelper *, dotNetShop

<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8" />
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="~/img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="@ViewData["Author"]">
	<!-- Meta Description -->
	<meta name="description" content="@ViewData["Description"]">
	<!-- Meta Keyword -->
	<meta name="keywords" content="@ViewData["Keywords"]">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>@ViewData["Title"]</title>
	<!--
		CSS
		============================================= -->
	<link rel="stylesheet" href="~/css/linearicons.css">
	<link rel="stylesheet" href="~/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/css/themify-icons.css">
	<link rel="stylesheet" href="~/css/bootstrap.css">
	<link rel="stylesheet" href="~/css/owl.carousel.css">
	<link rel="stylesheet" href="~/css/nice-select.css">
	<link rel="stylesheet" href="~/css/nouislider.min.css">
	<link rel="stylesheet" href="~/css/ion.rangeSlider.css" />
	<link rel="stylesheet" href="~/css/ion.rangeSlider.skinFlat.css" />
	<link rel="stylesheet" href="~/css/magnific-popup.css">
	<link rel="stylesheet" href="~/css/main.css" asp-append-version="true">




</head>
<body>

	<!-- Start Header Area -->
	<header class="header_area sticky-header">
		<div class="main_menu">
			<nav class="navbar navbar-expand-lg navbar-light main_box">
				<div class="container">

					<!-- Brand and toggle get grouped for better mobile display -->
					<a class="navbar-brand logo_h" asp-area="" asp-controller="Home" asp-action="Index">
						<img src="img/logo.png" alt="">
					</a>


					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
							aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>


					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
						<ul class="nav navbar-nav menu_nav ml-auto">
							<li class="nav-item active"><a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Главная</a></li>
							<li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Shop" asp-action="Index"> Магазин </a></></li>
							<li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Blog" asp-action="Index"> Блог </a></></li>
							<li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Contacts" asp-action="Index">Контакты</a></li>
							
							#<!-- #region name -->

							@* <li class="nav-item submenu dropdown">
								<a asp-area="" asp-controller="Shop" asp-action="Index" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								   aria-expanded="false">Магазин</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="category.html">Shop Category</a></li>
									<li class="nav-item"><a class="nav-link" href="single-product.html">Product Details</a></li>
									<li class="nav-item"><a class="nav-link" href="checkout.html">Product Checkout</a></li>
									<li class="nav-item"><a class="nav-link" href="cart.html">Shopping Cart</a></li>
									<li class="nav-item"><a class="nav-link" href="confirmation.html">Confirmation</a></li>
								</ul>
							</li> *@
							@* <li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								   aria-expanded="false">Blog</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
									<li class="nav-item"><a class="nav-link" href="single-blog.html">Blog Details</a></li>
								</ul>
							</li> *@
							@* <li class="nav-item submenu dropdown">
								<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
								   aria-expanded="false">Pages</a>
								<ul class="dropdown-menu">
									<li class="nav-item"><a class="nav-link" href="login.html">Login</a></li>
									<li class="nav-item"><a class="nav-link" href="tracking.html">Tracking</a></li>
									<li class="nav-item"><a class="nav-link" href="elements.html">Elements</a></li>
								</ul>
							</li> *@
							<!-- #endregion -->

						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li class="nav-item">
								<vc:account-menu></vc:account-menu>
							</li>
							<li class="nav-item"><a asp-action="Index" asp-controller="Cart" class="cart"><span class="ti-bag"></span></a></li>
							<li class="nav-item">
								<button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
		<div class="search_input" id="search_input_box">
			<div class="container">
				<form class="d-flex justify-content-between">
					<input type="text" class="form-control" id="search_input" placeholder="Поиск">
					<button type="submit" class="btn"></button>
					<span class="lnr lnr-cross" id="close_search" title="Закрыть"></span>
				</form>
			</div>
		</div>
	</header>

	<!-- End Header Area -->
	

	@RenderBody()

	@addTagHelper *, AspMvcAuth
	@{
		ViewData["Title"] = "Home Page";
	}

	<!-- start footer Area -->
	<footer class="footer-area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>About Us</h6>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore
							magna aliqua.
						</p>
					</div>
				</div>
				<div class="col-lg-4  col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Newsletter</h6>
						<p>Stay update with our latest</p>
						<div class="" id="mc_embed_signup">

							<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
								  method="get" class="form-inline">

								<div class="d-flex flex-row">

									<input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
										   required="" type="email">


									<button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
									<div style="position: absolute; left: -5000px;">
										<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
									</div>

									<!-- <div class="col-lg-4 col-md-4">
												<button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
											</div>  -->
								</div>
								<div class="info"></div>
							</form>
						</div>
					</div>
				</div>
				<div class="col-lg-3  col-md-6 col-sm-6">
					<div class="single-footer-widget mail-chimp">
						<h6 class="mb-20">Instragram Feed</h6>
						<ul class="instafeed d-flex flex-wrap">
							<li><img src="img/i1.jpg" alt=""></li>
							<li><img src="img/i2.jpg" alt=""></li>
							<li><img src="img/i3.jpg" alt=""></li>
							<li><img src="img/i4.jpg" alt=""></li>
							<li><img src="img/i5.jpg" alt=""></li>
							<li><img src="img/i6.jpg" alt=""></li>
							<li><img src="img/i7.jpg" alt=""></li>
							<li><img src="img/i8.jpg" alt=""></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-6 col-sm-6">
					<div class="single-footer-widget">
						<h6>Follow Us</h6>
						<p>Let us be social</p>
						<div class="footer-social d-flex align-items-center">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</div>
			<div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
				<p class="footer-text m-0">
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</p>
			</div>
		</div>
	</footer>
	<!-- End footer Area -->
	<!-- Begin Scripts section -->
	<script src="~/js/vendor/jquery-2.2.4.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
			crossorigin="anonymous"></script>
	<script src="~/js/vendor/bootstrap.min.js"></script>
	<script src="~/js/jquery.ajaxchimp.min.js"></script>
	<script src="~/js/jquery.nice-select.min.js"></script>
	<script src="~/js/jquery.sticky.js"></script>
	<script src="~/js/nouislider.min.js"></script>
	<script src="~/js/countdown.js"></script>
	<script src="~/js/jquery.magnific-popup.min.js"></script>
	<script src="~/js/owl.carousel.min.js"></script>
	<!--gmaps Js-->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
	<script src="~/js/gmaps.min.js"></script>
	<script src="~/js/main.js"></script>
	<!-- END Scripts section -->
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>